# Generated by Django 6.0.3 on 2026-04-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_banner_notice_alter_welcome_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='isdelete',
            new_name='is_delete',
        ),
    ]
