# Generated by Django 6.0.3 on 2026-04-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0003_rename_isdelete_banner_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
